name: publish

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  bundle_and_readme:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16

      - name: Build new README
        run: npm run generate-readme

      - name: Commit Readme
        run: |
          git config --local user.email "caiioocesar@outlook.com"
          git config --local user.name "Publish Action"
          git add README.md
          git commit -m "chore(CI) Generate bundles and Readme [skip ci]" -a
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
